// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhTetyC36cKPBu12gPtwNQjlMNFCEaJ5Q',
    appId: '1:73047100172:web:d95a72dc5c0d1debf61729',
    messagingSenderId: '73047100172',
    projectId: 'project-comics-e4272',
    authDomain: 'project-comics-e4272.firebaseapp.com',
    storageBucket: 'project-comics-e4272.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbw9LDAUGDjW8iKXtpKXlwmDqg6zi6CQ',
    appId: '1:73047100172:android:870f4e7a2cd9091ef61729',
    messagingSenderId: '73047100172',
    projectId: 'project-comics-e4272',
    storageBucket: 'project-comics-e4272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69t-3elrrMdo5SLBnuKT3CB7uA4QR1b0',
    appId: '1:73047100172:ios:ae0851012f1fe287f61729',
    messagingSenderId: '73047100172',
    projectId: 'project-comics-e4272',
    storageBucket: 'project-comics-e4272.appspot.com',
    iosClientId: '73047100172-plnhfgctvbdkh8rf2ro2o1ss317g0jlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectComics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69t-3elrrMdo5SLBnuKT3CB7uA4QR1b0',
    appId: '1:73047100172:ios:9929e392efbf3272f61729',
    messagingSenderId: '73047100172',
    projectId: 'project-comics-e4272',
    storageBucket: 'project-comics-e4272.appspot.com',
    iosClientId: '73047100172-k0mf05n0s6i3o6alalilq0e54mfg5of7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectComics.RunnerTests',
  );
}
